global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAVXJCNYLTIXRZ6SVE
        secret_key: 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
        port: 9100
